OOP school library: refactor your code
mmatongo/school-lib pull request #5
Opened 2021-11-15 08:08 UTC by mmatongo

### Project requirements

At this point your codebase is pretty big. The `main.rb` file may be especially large at this point. Let's try to clean things up!

- Make sure YAGNI, KISS, and DRY rules and Ruby style guide are respected.
- Follow SOLID principles.
- Pay special attention to the "Single-responsiblity Principle".
    - Make sure that the role of `main.rb` is only to start your code and ask the user for the initial choice of options (or to quit).
    - Extract some pieces of logic into separate class(es).
- **You need to use pair-programming for this project. We will check the commit history to make sure that both partners have contributed code on each project. Therefore you need to select one of the repos in your pair-programming group in which you will implement the above features.**

2021-11-15 09:51 UTC, mikethreels requested changes
Hi Muthomi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-15 09:51 UTC, mikethreels commented on handlers.rb
> +  end
- [ ] great job on the application 👍 you might want to make the `create_teacher` and `create_student` methods `private` for security and they are only used by the `create_person` method.
- [ ] also try to make use of the Single responsibility and the DRY rule, the `create_teacher` and `create_student` should only be used to check if it is a teacher or a student. you can get the name and age in the `create_person` method en push it to the `@people` instance variable as well so you don't have to do it twice.

2021-11-15 09:51 UTC, mikethreels commented on main.rb
>  def main
- [ ] Good job setting up the `Handlers` 💪 the `main` method seems to do very little at this point, in order to make your codebase more understandable you can make `main` start your code and ask the user for the initial choice of options like you're doing in `class App` right now and then you can put all the handler methods inside the class.

2021-11-15 10:05 UTC, mmatongo commented on main.rb
>  def main
Hey @mikethreels, the app is initialised inside `main`. It already does this from lines 59 - 62
https://github.com/mmatongo/school-lib/blob/bb488d2e2cdb83de49efde7018c9b5005c84208a/main.rb#L59-L62

2021-11-15 10:10 UTC, mikethreels commented on main.rb
>  def main
Hi Muthomi,

I know, I was actually more referring to the second part of my suggestion "ask the user for the initial choice of options"

2021-11-15 10:14 UTC, mmatongo commented on handlers.rb
> +  end
Hey @mikethreels the first point isn't as much a requirement as it is more optional.

Regarding the second point, the `create_teacher` and `create_student` do only one thing and that is collect the data and push it into the people array, moving their logic into the `create_person` does the exact same thing with even more steps because it would then require a lot of external referencing.
It's a redundant change because it changes nothing, the logic inside the `create_person` will become more obfuscated and go agains't the use of single responsibility which currently the code is doing just fine.

2021-11-15 10:21 UTC, mmatongo commented on main.rb
>  def main
> I know, I was actually more referring to the second part of my suggestion "ask the user for the initial choice of options"

I don't understand what you mean, when the application is initialised the user is presented with the options `app.run`.
As is the application does exactly what you're requiring a change for

2021-11-15 10:29 UTC, mmatongo commented on main.rb
>  def main
@mikethreels this is the initial choice of options you're referring to is triggered by the main method, we already went over this last week.
https://github.com/mmatongo/school-lib/pull/4#discussion_r745147231

![Screenshot 2021-11-15 at 12 23 51 PM](https://user-images.githubusercontent.com/40806126/141765440-243e6966-0d7c-4fa9-b1cc-cdc8b896b892.png)

2021-11-15 11:16 UTC, mikethreels commented on main.rb
>  def main
@mmatongo yes exactly as I explained it there, according to[ the list of requirements ](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_refactor.md)you get the `main` method should also ask for the user's initial choice of options.

2021-11-15 11:37 UTC, mikethreels commented on handlers.rb
> +  end
Hi @mmatongo what I'm referring to in this case is the below part
```
    print 'Age: '
    age = gets.chomp

    print 'Name: '
    name = gets.chomp

```

you write exactly the same in both functions which is not according to the DRY method, you can put this inside the `create_person` method instead. which makes it still according to the single responsibility.

2021-11-15 11:45 UTC, mmatongo commented on main.rb
>  def main
That's not part of these requirements, those are your own requirements.

Secondly look at the main method, I start the application then call app.run to to give the user the new set of options, how do you not see that inside the code?

2021-11-15 11:53 UTC, mmatongo commented on handlers.rb
> +  end
Those are handled separately because because after they input their names and ages the call to actions become different with one being `specialisation` and the other being `parent_permission`

2021-11-15 12:10 UTC, mmatongo commented on main.rb
>  def main
Also you're wrong, the requirements say

>Make sure that the role of main.rb is only to start your code and ask the user for the initial choice of options (or to quit).

`main.rb` not `main` method
Which is exactly what has been implemented

2021-11-15 14:06 UTC, mikethreels commented on main.rb
>  def main
@mmatongo, These are not my own requirements, at this point, it might be best if you request a meeting with a senior CR so they can explain the project requirements.

2021-11-15 14:29 UTC, mmatongo commented on handlers.rb
> +  end
This has been resolved.

2021-11-15 14:43 UTC, mmatongo commented on main.rb
>  def main
> @mmatongo, These are not my own requirements, at this point, it might be best if you request a meeting with a senior CR so they can explain the project requirements.


As I mentioned above, the requirements state that the `main.rb` should maintain that functionality of starting the code and giving the user the initial choice of options.
As is, the code currently in the `main.rb` does this.


What you've been telling me to do is to make it so that this functionality is contained within the `main` method which is not part of the requirements, but irregardless my code still achieves this from within the `main` method here
https://github.com/mmatongo/school-lib/blob/bb488d2e2cdb83de49efde7018c9b5005c84208a/main.rb#L59-L62

2021-11-15 16:16 UTC, mikethreels approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-15 17:53 UTC, mmatongo commented
> Hi team,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it 🚀 : Congratulations! 🎉

Thanks

2021-11-15 17:53 UTC, merged

2021-12-03 10:28 UTC, bellom commented
Hello 👋,

This is an additional review as a result of the second opinion request.

Looks like the issue was resolved here, so I have nothing else to say other than best of luck with the rest of your projects!

Keep rocking 🚀!